name: Build 32-bit NOESCAPE EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Download 32-bit MinGW
        run: |
          curl -L -o mingw.7z https://github.com/niXman/mingw-builds-binaries/releases/download/12.2.0-rt_v10-rev0/i686-12.2.0-release-win32-sjlj-rt_v10-rev0.7z
          7z x mingw.7z -oC:\mingw

      - name: Compile as 32-bit EXE
        run: |
          C:\mingw\bin\g++.exe esc_trigger.cpp -o esc_trigger.exe
        shell: cmd

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: NOESCAPE-32bit
          path: esc_trigger.exe
