name: Build NOESCAPE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.1

      - name: Compile with cl.exe
        shell: cmd
        run: |
          call "%VSINSTALLDIR%VC\Auxiliary\Build\vcvarsall.bat" x64
          cl esc_trigger.cpp /Fe:esc_trigger.exe

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: NOESCAPE-exe
          path: esc_trigger.exe
