name: Build NOESCAPE EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile ESC Trigger
      run: |
        cl esc_trigger.cpp /Fe:esc_trigger.exe

    - name: Prepare SED File
      run: |
        echo > noescape.sed [
        echo ] >> noescape.sed
        echo .CreateNewPackage=1 >> noescape.sed
        echo .PackagePurpose=InstallApp >> noescape.sed
        echo .ShowInstallProgramWindow=1 >> noescape.sed
        echo .HideExtractAnimation=1 >> noescape.sed
        echo .InstallPrompt=%COMSPEC% /c start.bat >> noescape.sed
        echo .PostInstallCmd=%COMSPEC% /c start.bat >> noescape.sed
        echo .TargetName=NOESCAPE.exe >> noescape.sed
        echo .SourceFiles=SourceFiles >> noescape.sed
        echo [SourceFiles] >> noescape.sed
        echo SourceFiles0=. >> noescape.sed
        echo [SourceFiles0] >> noescape.sed
        echo .Files=start.bat,spill.vbs,fake_login.html,recover.vbs,esc_trigger.exe,startup.wav,open_me.txt >> noescape.sed

    - name: Bundle with IExpress
      run: |
        iexpress /n /q noescape.sed

    - name: Upload Final EXE
      uses: actions/upload-artifact@v3
      with:
        name: NOESCAPE
        path: NOESCAPE.exe
